name: carregar_empresa_package
description: Package de carregamento dos dados da empresa Ã  partir do banco de dados.
version: 1.1.2
homepage: https://github.com/pwlimaverde/carregar_empresa_package.git

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  return_success_or_error: ^0.1.7
  flutter:
    sdk: flutter

dev_dependencies:
  rxdart: ^0.26.0-nullsafety.1
  mocktail: ^0.0.1-dev.10
  flutter_test:
    sdk: flutter

flutter: